// products data
const products = [
  {
    id: 'uid01',
    name: 'Pink Fitness Tracker',
    src: '/images/product/a.jpg',
    sku: '0533009',
    qty: '42',
    price: '126.00',
    status: 'Published',
    rating: 5,
  },
  {
    id: 'uid02',
    name: 'Pool Party Drink Holder',
    src: '/images/product/b.jpg',
    sku: '0253800',
    qty: '12',
    price: '35.99',
    status: 'Scheduled',
    rating: 4,
  },
  {
    id: 'uid03',
    name: 'AliExpress Fitness Trackers',
    src: '/images/product/c.jpg',
    sku: '0253804',
    qty: '15',
    price: '135.99',
    status: 'Inactive',
    rating: 3,
  },
  {
    id: 'uid04',
    name: 'iPhone 7 Headphones',
    src: '/images/product/d.jpg',
    sku: '0253807',
    qty: '13',
    price: '45.99',
    status: 'Inactive',
    rating: 3,
  },
  {
    id: 'uid05',
    name: 'Purple Blue Gradient iPhone Case',
    src: '/images/product/e.jpg',
    sku: '0253808',
    qty: '0',
    price: '145.99',
    status: 'Inactive',
    rating: 2,
  },
  {
    id: 'uid06',
    name: 'Wireless Waterproof Speaker',
    src: '/images/product/f.jpg',
    sku: '0253808',
    qty: '23',
    price: '14.99',
    status: 'Published',
    rating: 4,
  },
  {
    id: 'uid07',
    name: 'Black Headphones',
    src: '/images/product/g.jpg',
    sku: '0253809',
    qty: '11',
    price: '144.99',
    status: 'Published',
    rating: 4,
  },
  {
    id: 'uid08',
    name: 'Flared Shift Dress',
    src: '/images/product/h.jpg',
    sku: '0253806',
    qty: '11',
    price: '34.99',
    status: 'Scheduled',
    rating: 5,
  },
  {
    id: 'uid09',
    name: 'Nio Extended Camera',
    src: '/images/product/i.jpg',
    sku: '0253806',
    qty: '17',
    price: '134.99',
    status: 'Inactive',
    rating: 3,
  },
  {
    id: 'uid10',
    name: 'Battery Charger',
    src: '/images/product/j.jpg',
    sku: '0253806',
    qty: '21',
    price: '134.99',
    status: 'Inactive',
    rating: 4,
  },
  {
    id: 'uid11',
    name: 'Laptop Case Bag',
    src: '/images/product/k.jpg',
    sku: '0253806',
    qty: '22',
    price: '134.99',
    status: 'Published',
    rating: 3,
  },
  {
    id: 'uid12',
    name: 'Digital Camera 16x',
    src: '/images/product/l.jpg',
    sku: '0253802',
    qty: '22',
    price: '134.99',
    status: 'Scheduled',
    rating: 2,
  },
  {
    id: 'uid13',
    name: 'Casual Note Bag',
    src: '/images/product/m.jpg',
    sku: '0253802',
    qty: '65',
    price: '13.99',
    status: 'Published',
    rating: 5,
  },
  {
    id: 'uid14',
    name: 'Blue Gentle Shoes',
    src: '/images/product/n.jpg',
    sku: '0253802',
    qty: '0',
    price: '13.99',
    status: 'Inactive',
    rating: 3,
  },
  {
    id: 'uid15',
    name: 'Casual Blue Shoes',
    src: '/images/product/o.jpg',
    sku: '0253800',
    qty: '4',
    price: '13.99',
    status: 'Published',
    rating: 4,
  },
  {
    id: 'uid16',
    name: 'Black Grey Headset',
    src: '/images/product/p.jpg',
    sku: '0253806',
    qty: '24',
    price: '113.99',
    status: 'Published',
    rating: 4,
  },
]

export default products
